#!/usr/bin/env ruby

require_relative 'config.rb'
require_relative 'options.rb'

mods = Array.new
changed = Hash.new

Dir.foreach('./mod') do |mod|
	mods << mod.gsub("\.rb",'') unless (mod == '.' || mod == '..')	
end

mods.each do |m|
	require_relative 'mod/' + m + '.rb'
end

config = Config.new(ARGV[0])

confs = config.parse

opts = Options.new('options.json').parse

notiMethod = opts["global"]["notification"]

threads = Array.new

confs.each_value do |pkg|

	name = pkg['name']
	mod = pkg['mod']
	url = pkg['url']
	oldver = pkg['version']

	thread = Thread.new {
		if mods.include?(mod)
			newver = Object.const_get(mod.capitalize).new(url,oldver).check

			unless oldver == 'nil'
				if newver > oldver
					p "there's new release #{newver} for #{name}"
					changed[name] = [oldver,newver]
				end
			else
				p "there's new release #{newver} for #{name}"
				changed[name] = [oldver,newver]
			end
		end
	}

	threads << thread

end

threads.each { |t| t.join }
config.write(changed) unless changed.empty?
