require 'net/smtp'

module UpstreamNotifier
  class Email
    def initialize(option, *args)
      @option = option[self.class.to_s.split('::')[1].downcase!]
      @name, @version = args
    end

    def get
      message = <<MESSAGE_END
From: Upstream Notifier <
To:
Subject: [UpstreamNotifier] #{@name} has a new release #{@version}

DO NOT REPLY!

UpstreamNotifier just found a new release #{@version} for #{@name}
, please update ASAP!

Brief Changelog:

...

Generated by Upstream Notifier from marguerite <marguerite@opensuse.org>
If feel bothered or meet any trouble, please contact.
MESSAGE_END

      smtp = Net::SMTP.new @option['server'], @option['port']
      smtp.enable_starttls
      smtp.start('gmail.com', @option['from'], @option['password'], :login) do
        smtp.send_message(message, @option['from'], @option['to'])
      end
    end
  end
end
