---
libzhuyin:
  version: 1.0.91
  plugin: github
  url: https://github.com/libzhuyin/libzhuyin
ibus-libzhuyin:
  version: 1.7.4
  plugin: github
  url: https://github.com/libzhuyin/ibus-libzhuyin
fcitx-zhuyin:
  version: 4.2.9_dict+git20150626.36064e1
  plugin: github
  url: https://github.com/fcitx/fcitx-zhuyin
brise:
  version: 0.36+git20150824.40b697b
  plugin: github
  url: https://github.com/rime/brise
librime:
  version: 1.2.9+git20150802.ee3029e
  plugin: github
  url: https://github.com/rime/librime
ibus-rime:
  version: 1.2.9+git20150802.ee3029e
  plugin: github
  url: https://github.com/lotem/ibus-rime
fcitx-rime:
  version: 4.2.9_dict+git2015083.b716234
  plugin: github
  url: https://github.com/fcitx/fcitx-rime
sunpinyin:
  version: 2.0.4+git2015076.cf18102
  plugin: github
  url: https://github.com/sunpinyin/sunpinyin
googletest:
  version: release-1.7.0+git20150827.d945d8c
  plugin: github
  url: https://github.com/google/googletest
presage:
  version: 0.9.1
  plugin: sourceforge
  url: http://presage.sourceforge.net
opencc:
  version: ver.1.0.3
  plugin: github
  url: https://github.com/BYVoid/OpenCC
libhangul:
  version: 0.1.0+git20150224.78e9d89
  plugin: github
  url: https://github.com/choehwanjin/libhangul
imhangul:
  version: 3.1.1+git20130112.a4c2796
  plugin: github
  url: https://github.com/choehwanjin/imhangul
libpinyin:
  version: 1.2.0+git20150731.958c597
  plugin: github
  url: https://github.com/libpinyin/libpinyin
libchewing:
  version: 0.4.0+git20150830.d3a7a0b
  plugin: github
  url: https://github.com/chewing/libchewing
libkkc:
  version: 0.3.5+git20150522.650f0d6
  plugin: github
  url: https://github.com/ueno/libkkc
libskk:
  version: 1.2.0+git20150413.be6e20b
  plugin: github
  url: https://github.com/ueno/libskk
gnugo:
  version: rel-3-9-1+git20130613.84a32e9
  plugin: cgit
  url: http://git.savannah.gnu.org/cgit/gnugo.git
rubygem-qtbindings:
  version: 4.8.6.2
  plugin: rubygems
  url: qtbindings
perl-Devel-Cover:
  version: '1.20'
  plugin: cpan
  url: Devel::Cover
python-faulthandler:
  version: '2.4'
  plugin: pypi
  url: faulthandler
python-leveldb:
  version: '0.193'
  plugin: pypi
  url: leveldb
fcitx-anthy:
  version: 0.2.2
  plugin: fcitx
  url: fcitx-anthy
fcitx-chewing:
  version: 0.2.2
  plugin: fcitx
  url: fcitx-chewing
fcitx-cloudpinyin:
  version: 0.3.4
  plugin: fcitx
  url: fcitx-cloudpinyin
fcitx-configtool:
  version: 0.4.8
  plugin: fcitx
  url: fcitx-configtool
fcitx-fbterm:
  version: 0.2.0
  plugin: fcitx
  url: fcitx-fbterm
fcitx-googlepinyin:
  version: 0.1.6
  plugin: fcitx
  url: fcitx-googlepinyin
fcitx-hangul:
  version: 0.3.0
  plugin: fcitx
  url: fcitx-hangul
fcitx-kkc:
  version: 0.1.2
  plugin: fcitx
  url: fcitx-kkc
fcitx-libpinyin:
  version: 0.3.2_dict
  plugin: fcitx
  url: fcitx-libpinyin
fcitx-m17n:
  version: 0.2.3
  plugin: fcitx
  url: fcitx-m17n
fcitx-qt5:
  version: ver.1.0.4
  plugin: fcitx
  url: fcitx-qt5
fcitx-sayura:
  version: 0.1.1
  plugin: fcitx
  url: fcitx-sayura
fcitx-skk:
  version: 0.1.2
  plugin: fcitx
  url: fcitx-skk
fcitx-sunpinyin:
  version: 2.0.4+git2015076.cf18102
  plugin: fcitx
  url: fcitx-sunpinyin
fcitx-table-extra:
  version: 0.3.7
  plugin: fcitx
  url: fcitx-table-extra
fcitx-table-other:
  version: 0.2.3
  plugin: fcitx
  url: fcitx-table-other
fcitx-unikey:
  version: 0.2.4
  plugin: fcitx
  url: fcitx-unikey
kcm5-fcitx:
  version: 0.5.0
  plugin: fcitx
  url: kcm-fcitx
fcitx-ui-light:
  version: 0.1.3
  plugin: fcitx
  url: fcitx-ui-light
