---
golang-github-russross-blackfriday:
  version: v1.4
  plugin: github
  url: https://github.com/russross/blackfriday
  version: v1.0.5
  plugin: github
  url: https://github.com/cpuguy83/go-md2man
