---
golang-github-russross-blackfriday:
  version: v1.4
  plugin: github
  url: russross/blackfriday
  notifier: email
  maintainer: example@example.com
golang-github-cpuguy83-go-md2man:
  version: v1.0.5
  plugin: github
  url: cpuguy83/go-md2man
  notifier: email
  maintainer: example@example.com
