---
doubanfm-qt5:
  version: 2.1.0
  plugin: github
  url: zonyitoo/doubanfm-qt
  notifier: email
  maintainer: example@example.com
WeCase:
  version: 0.0.6
  plugin: github
  url: WeCase/WeCase
  notifier: email
  maintainer: example@example.com
python3-rpweibo:
  version: 0.02.2
  plugin: github
  url: WeCase/rpweibo
  notifier: email
  maintainer: example@example.com
python3-notify2:
  version: '0.3'
  plugin: pypi
  url: notify2
  notifier: email
  maintainer: example@example.com
